#![no_std]
#![feature(
    try_trait,
    concat_idents,
    const_fn,
    repr_transparent,
)]

#[macro_use]
extern crate bitflags;

pub use self::error::*;
pub use self::common::*;

/// ABI calls
#[cfg(feature = "wasm")]
pub mod abi;

/// All the errors that can be generated by abi calls
pub mod error;

pub mod common;

#[macro_export]
macro_rules! internal_error {
    () => {{
        if cfg!(debug_assertions) {
            println!("Internal Error At {} : {}", file!(), line!());
        }
        $crate::Error::INTERNAL
    }}
}